/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")

    implementation("org.apache.commons:commons-text")
    implementation(project(":lib"))
    implementation(files("libs/AuthCat-Java.jar"))
    implementation(files("libs/Java-WebSocket-1.5.7.jar"))
    implementation(files("libs/json-simple-1.1.1.jar"))

    // Source: https://mvnrepository.com/artifact/org.slf4j/slf4j-api
    implementation("org.slf4j:slf4j-api:2.0.17")
}

application {
    // Define the main class for the application.
    mainClass = "net.nathcat.peoplecat_server.Main"
}
