/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(files("libs/json-simple-1.1.1.jar"))
    implementation(files("libs/mysql-connector-j-8.0.33.jar"))

    // https://mvnrepository.com/artifact/com.google.code.gson/gson
    implementation("com.google.code.gson:gson:2.13.2")
}
